[package]
name = "floq-timetracker-cli"
version = "0.1.0"
authors = ["emil daijiro <eg@blank.no>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
reqwest = { version = "0.10", features = ["json", "blocking"] }
tokio = { version = "0.2", features = ["full"] }
serde = { version = "1.0.115", features = ["derive"] }
clap = "3.0.0-beta.1"