[package]
name = "floq-timetracker-cli"
version = "0.1.0"
authors = ["emil daijiro <eg@blank.no>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
async-std = "1.6.5"
futures = "0.3.6"
surf = "2.0.0"
serde = { version = "1.0.115", features = ["derive"] }
serde_json = "1.0"
chrono = { version = "0.4", features = ["serde"] }
dotenv = { version = "0.15.0" }
clap = "3.0.0-beta.1"

[dev-dependencies]
demonstrate = { version = "0.4.5" }
