name: Rust

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: actions-rs/install@v0.1
      with:
        crate: clippy
        version: latest
        use-tool-cache: true
    - name: Lint
      run: cargo clippy -- -D warnings 
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose
